version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  node: circleci/node@4.7

executors:
  macos:
    macos:
      xcode: 14.2.0

jobs:
  test:
    parameters:
      os:
        type: executor
      test:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Enable opening app not codesigned
          command: sudo spctl --master-disable
      - run:
          name: Extract the app
          command: |
            cp -r apps/Uplink.app /Applications/
            sudo xattr -r -d com.apple.quarantine /Applications/Uplink.app
      - run:
          name: Install NPM dependencies
          command: npm ci
      - run:
          name: Install and Run Appium Server
          command: |
            npm install -g appium@next
            appium -v
            appium driver install mac2
            appium driver list
      - run:
          name: Delete Cache Folder if exists
          command: rm -rf ~/.uplink
      - run:
          name: Run WebdriverIO tests on MacOS
          command: npm run << parameters.test >>
      - store_test_results:
          path: test-report/*.xml
          destination: junit-report-<< parameters.test >>
          when: always
      - store_artifacts:
          path: test-results
          destination: appium-screenshots-<< parameters.test >>
          when: on_fail
      - store_artifacts:
          path: appium.log
          destination: appium-log-<< parameters.test >>
          when: on_fail

workflows:
  test:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - test
          matrix:
            parameters:
              os: [macos]
              test: ["mac.chatA","mac.chatB"]
